name: Deploy OAuth Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "auth-service/**"
      - "k8s/auth.yaml"
      - ".github/workflows/deploy-oauth-service.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup K8s config
      - name: Set up K8s config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      # Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kieger
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build + push image
      - name: Build and push Docker image
        run: |
          docker build -t kieger/oauth-service:latest auth-service
          docker push kieger/oauth-service:latest

      # Apply Kubernetes Secret
      - name: Apply Kubernetes Secret
        run: |
          kubectl delete secret oauth-secret --ignore-not-found=true
          kubectl create secret generic oauth-secret \
            --from-literal=MASTER_DATABASE_URL="${{ secrets.MASTER_DATABASE_URL }}" \
            --from-literal=MASTER_DATABASE_USER="${{ secrets.MASTER_DATABASE_USER }}" \
            --from-literal=MASTER_DATABASE_PWD="${{ secrets.MASTER_DATABASE_PWD }}" \
            --from-literal=MAIL_USER="${{ secrets.MAIL_USER }}" \
            --from-literal=MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
            --from-literal=GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --from-literal=GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"

      # Deploy to K8s
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/auth.yaml
          kubectl rollout restart deployment oauth-service
