name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Kubernetes access
      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      # Build + Push Docker image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kieger
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t kieger/frontend:latest ./frontend
          docker push kieger/frontend:latest

      # Apply Deployment + Service + Ingress
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-ingress.yaml
          kubectl rollout restart deployment frontend
