name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - "k8s/frontend-*.yaml"
      - ".github/workflows/frontend-oauth.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup K8s config
      - name: Set up K8s config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      # Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kieger
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build + push image
      - name: Build and push Docker image
        run: |
          docker build -t kieger/frontend:latest frontend
          docker push kieger/frontend:latest

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-ingress.yaml
          kubectl rollout restart deployment frontend
